### ISSUE TITLE
Broken room I-01b from 9CC

### ISSUE THREAD

**Issue by emmflo** [Mnstrman06/Celeste-Modded-Randomizer#2]
Hello,

I softlocked playing CC-sides in the randomizer.
Here is a link to a video showing the softlock: https://www.youtube.com/watch?v=t4QP5o9OatA
The fish gets stuck on the ledge instead of getting launched by the spring.

Thanks for the fun mod ^^
Emma

**Comment by Mnstrman06** [comment]
i can't figure out what causes this, i've seen this in the past but i just figured it was a regular issue with 9cc itself. it appears this issue is something to do with specifically randomizer, and i dont know why

**Comment by Mnstrman06** [comment]
for now i might just take this room out of rotation, seems i cant really do much. theres probably some weird tweak stuff i could do but if this is a problem with the randomizer itself then i want to get the bug fixed

**Comment by Mnstrman06** [comment]
fixed this room i think by moving spring by 1 pixel, not sure why it happens still but i did fix
